# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java

jdk:
  - oraclejdk8

before_install:
  # For running JavaFX testing in CI environment. 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37f906849ec37ab6a7c1
    on_success: always
    on_failure: always
    on_start: never