language: java

jdk:
  - oraclejdk8

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37f906849ec37ab6a7c1
    on_success: always
    on_failure: always
    on_start: never